name: neon_music_player
description: A premium offline Flutter music player with a Sky Blue Neon glassmorphism identity.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Audio scanning + metadata
  on_audio_query: ^2.9.0

  # Playback engine
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.13
  audio_session: ^0.1.21

  # Persistence
  shared_preferences: ^2.2.3

  # Permissions
  permission_handler: ^11.3.1

  # UI / visuals
  google_fonts: ^6.2.1
  palette_generator: ^0.3.3+3
  marquee: ^2.2.3

  # Utilities
  uuid: ^4.4.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
